# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Research Paper Summaries
tagline:             'by Spandan Madan'
description:         ''
url:                 https://spandan-madan.github.io/paper-summaries/
baseurl:             ''
paginate:            5
gems: [jekyll-paginate]
paginate_path: "page:num"


# About/contact
author:
  name:              Spandan Madan
  url:               people.csail.mit.edu/smadan/web
  email:             smadan@mit.edu

# Custom vars
version:             1.0.0
